// Copyright (C) Benjamín Gajardo (also known as +KZ)

#ifndef GAME_VERSION_KZ_H
#define GAME_VERSION_KZ_H

#define KAIZO_NETWORK_VERSION_DDNET // No Custom Messages
#define KAIZO_NETWORK_VERSION_CROWNS 1
#define KAIZO_NETWORK_VERSION_TURRETS 2
#define KAIZO_NETWORK_VERSION_PORTAL_ATTRACTOR 3

#define KAIZO_NETWORK_VERSION_LATEST KAIZO_NETWORK_VERSION_PORTAL_ATTRACTOR

#endif